### ISSUE TITLE
Model file missing

### ISSUE THREAD

**Issue by santo4ul** [arnaldog12/Deep-Learning#6]
Hi, I couldn't find the models folder. Could you please share instructions to download the model?

├── data (unzip dataset here)
├── images
├── models
├── Keras.ipynb

**Comment by arnaldog12** [comment]
Hi, @santo4ul 
the model will be trained by you by running the notebook. However, you must create the `models` folder before running the notebook to ensure the notebook can save the model in the appropriate folder.

I hope it helps.
