### ISSUE TITLE
Question: Re-training using 5 landmark points

### ISSUE THREAD

**Issue by santo4ul** [arnaldog12/Deep-Learning#7]
Hi, Thanks for the inputs you shared on [#6](https://github.com/arnaldog12/Deep-Learning/issues/6). The result looks good. Training was quite easy!

I'm planning to use the same method, but only with 5 landmark points (left and right eye center,  nose tip, right and left mouth corners). The reason is that, MTCNN face detector outputs 5 landmark points and I'm planning to re-use the same and there by avoiding the dlib shape predictor.

Could you share your inputs? I agree that the number of features with 5 points would be very less when compared to 68 points. However, I'd like to get your inputs. 

Thanks,
San

**Comment by arnaldog12** [comment]
I'm sorry, @santo4ul, but I don't have the inputs anymore neither the code to generate them. However, it's easy to use Dlib in Python to detect faces. You can use either the [this post](https://www.pyimagesearch.com/2017/04/03/facial-landmarks-dlib-opencv-python/) or [this repo](https://github.com/ageitgey/face_recognition) as reference. 

You can also check my [Medium post](https://medium.com/analytics-vidhya/face-pose-estimation-with-deep-learning-eebd0e62dbaf) to see more details about how I computed the features.

Please, close this issue if you have no more questions.

**Comment by santo4ul** [comment]
Thanks a lot @arnaldog12  for your inputs. I'll close the ticket.
